import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navigation/navbar";


const inter = localFont({
  src:"./font/Inter.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700"

});

const space = localFont({
  src:"./font/space.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/site-logo.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.className, space.variable)}
      suppressHydrationWarning
    >
      <body className={` ${inter.className} ${space.variable} min-h-full flex flex-col`}>
        
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
        </ThemeProvider>
        
        
        </body>
    </html>
  );
}
