import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const inter = localFont({
  src:"./font/Inter.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700"

});

const space = localFont({
  src:"./font/space.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/site-logo.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${space.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        
        {children}</body>
    </html>
  );
}
