import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";




const inter = localFont({
  src:"./font/Inter.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700"

});

const space = localFont({
  src:"./font/space.ttf",
  variable: "--font-space-grotesk",
  weight: "300 400 500 600 700"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/site-logo.svg",
  }
};

export default async function RootLayout({children}: {children: React.ReactNode}) {

  const sessionProvider = await auth();

  return (

    
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.className, space.variable)}
      suppressHydrationWarning
    >
      <SessionProvider session={sessionProvider} >
      <body className={` ${inter.className} ${space.variable} min-h-full  flex flex-col`}>
        
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
    
            {children}
      
        </ThemeProvider>
        <Toaster />
        
        </body>
    </SessionProvider>
      

        
    </html>
  );
}

